#!/usr/bin/env node
// Builds the DSP core.
//   node core/build.mjs           → core/ll_core.wasm + core/ll_params.js, then the native tests
//   node core/build.mjs --no-test  skip the native build/tests
// The wasm is COMMITTED (like vendor/): building it needs an LLVM with the
// WebAssembly backend, which Xcode's clang does not ship, so `npm run build`
// only inlines it. Rebuild here after touching core/src.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const here = dirname(fileURLToPath(import.meta.url));
const src = readdirSync(join(here, "src")).filter(f => f.endsWith(".c")).map(f => join(here, "src", f));
const noTest = process.argv.includes("--no-test");
const run = (cmd, args) => { try { return execFileSync(cmd, args, { stdio: ["ignore", "pipe", "pipe"] }).toString(); }
  catch (e) { console.error((e.stderr || e.stdout || e.message).toString()); process.exit(1); } };

// 1. Exports = every ll_* function declared in ll.h.
const hdr = readFileSync(join(here, "ll.h"), "utf8");
const exports = [...hdr.matchAll(/^\s*(?:[\w*]+\s+)+\*?\s*(ll_\w+)\s*\(/gm)].map(m => m[1]);
const uniq = [...new Set(exports)];

// 2. Param tables for the JS host, generated from the enums so they can't drift.
const enumOf = (name) => {
  const m = hdr.match(new RegExp(`enum ${name} \\{([\\s\\S]*?)\\};`));
  if (!m) throw new Error("enum " + name + " not found");
  const out = {}; let i = 0;
  for (const line of m[1].split("\n")) {
    const s = line.replace(/\/\*.*?\*\//g, "").trim(); if (!s) continue;
    for (const tok of s.split(",")) { const k = tok.trim().split(/[=\s]/)[0]; if (!k || !/^LL_/.test(k)) continue; if (/COUNT$/.test(k)) continue; out[k.replace(/^LL_(P|L|D|EV)_/, "")] = i++; }
  }
  return out;
};
const params = { P: enumOf("ll_param"), L: enumOf("ll_lparam"), D: enumOf("ll_dparam"), EV: enumOf("ll_event") };
// events are 1-based in the header
for (const k of Object.keys(params.EV)) params.EV[k] += 1;
writeFileSync(join(here, "ll_params.js"), "// Generated by core/build.mjs from core/ll.h — do not edit.\nconst LL_PARAMS=" + JSON.stringify(params) + ";\n");

// 3. wasm. No libc: -nostdlib, own memcpy/memset, own math. -ffp-contract=off so
// the native test build and the wasm agree bit for bit (neither may fuse).
const common = ["-O2", "-ffp-contract=off", "-fno-builtin", "-fno-strict-aliasing", "-Wall", "-Wno-unused-function"];
const wasmOut = join(here, "ll_core.wasm");
run("clang", ["--target=wasm32", ...common, "-nostdlib", "-Wl,--no-entry", "-Wl,-z,stack-size=1048576",
  ...uniq.map(e => `-Wl,--export=${e}`), "-o", wasmOut, ...src]);
const wasmKB = Math.round(readFileSync(wasmOut).length / 1024);
console.log(`core: ll_core.wasm (${wasmKB}KB), ${uniq.length} exports, ${Object.keys(params.P).length}/${Object.keys(params.L).length}/${Object.keys(params.D).length} params`);

// 4. Native tests.
if (!noTest) {
  const tdir = join(here, "test"); const bdir = join(tdir, "build"); if (!existsSync(bdir)) mkdirSync(bdir);
  for (const t of readdirSync(tdir).filter(f => f.endsWith(".c"))) {
    const exe = join(bdir, t.replace(/\.c$/, ""));
    run("cc", [...common, "-I", here, "-o", exe, join(tdir, t), ...src, "-lm"]);
    let out = "";
    try { out = execFileSync(exe, [bdir], { stdio: ["ignore", "pipe", "pipe"] }).toString(); }
    catch (e) { out = (e.stdout || "").toString() + (e.stderr || "").toString(); process.stdout.write(out); process.exit(1); }
    process.stdout.write(out);
  }
  // wasm ⇔ native equivalence (needs the smoke's f32 dump above).
  process.stdout.write(run(process.execPath, [join(tdir, "wasm.mjs")]));
}
